version: "3.8"
services:
  whereami-live:
    build: .
    container_name: whereami-live
    restart: unless-stopped
    ports:
      - "3003:3003"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3003
